# action.yml
name: 'pascal22p/Scala SBT Action'
author: 'Pascal Parois <pascal22p@parois.net>'
description: 'SBT build tool action with docker'
inputs:
  command:  # id of input
    description: 'Commands to run'
    required: true
  working-directory:
    description: 'A directory to run SBT in'
    required: false
    default: .
  docker-login-username:  # Docker login username
    description: 'docker login username'
    required: false
  docker-login-password:  # Docker login password
    description: 'docker login password'
    required: false
  docker-registry:  # Docker registry
    description: 'docker registry, defaults to DockerHub'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.docker-login-username }}
    - ${{ inputs.docker-login-password }}
    - ${{ inputs.docker-registry }}
    - ${{ inputs.working-directory }}

branding:
  icon: 'package'
  color: 'blue'
